// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb2qkxypvSPEeNJVpNqM3tjsXF3PBFnQ0',
    appId: '1:117579185695:web:20db61150eed2c3ab95f2a',
    messagingSenderId: '117579185695',
    projectId: 'pmsn20252',
    authDomain: 'pmsn20252.firebaseapp.com',
    storageBucket: 'pmsn20252.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDobhnA9LIUPnjhsfa6UwaLeNicOLZPtY',
    appId: '1:117579185695:android:005b77d093346071b95f2a',
    messagingSenderId: '117579185695',
    projectId: 'pmsn20252',
    storageBucket: 'pmsn20252.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9GaM4-dbVFqhoeYbU1UbeheYkBPn6x0Y',
    appId: '1:117579185695:ios:67dbd4df6b3b887cb95f2a',
    messagingSenderId: '117579185695',
    projectId: 'pmsn20252',
    storageBucket: 'pmsn20252.firebasestorage.app',
    iosBundleId: 'com.example.pmsn20252',
  );

}